[[s_getting_started]]
[#ch01-introduction]
= Démarrage rapide

Ce chapitre traite du démarrage rapide avec Git.
Nous commencerons par expliquer les bases de la gestion de version, puis nous parlerons de l'installation de Git sur votre système et finalement du paramétrage pour commencer à l'utiliser.
À la fin de ce chapitre vous devriez en savoir assez pour comprendre pourquoi on parle beaucoup de Git, pourquoi vous devriez l'utiliser et vous devriez en avoir une installation prête à l'emploi.

include::book/01-introduction/sections/about-version-control.asc[]

include::book/01-introduction/sections/history.asc[]

include::book/01-introduction/sections/basics.asc[]

include::book/01-introduction/sections/command-line.asc[]

include::book/01-introduction/sections/installing.asc[]

include::book/01-introduction/sections/first-time-setup.asc[]

include::book/01-introduction/sections/help.asc[]

== Résumé

Vous devriez avoir à présent une compréhension initiale de ce que Git est et en quoi il est différent des CVCS que vous pourriez déjà avoir utilisés.
Vous devriez aussi avoir une version de Git en état de fonctionnement sur votre système, paramétrée avec votre identité.
Il est temps d'apprendre les bases d'utilisation de Git.
