== Translation Notes

Ces notes documentent le processus de traduction du livre en français.
C'est surtout par rapport au choix des mots et des expressions et ne doit être d'aucun intérêt pour un lecteur ou un traducteur non-français.

== Lexique

=== Repository

  Dépôt

=== Check in

  Dépôt

=== To check in

  Déposer, mettre en dépôt, faire un dépôt.

  Ex.
    To check a file in => Déposer un fichier
    When checking a directory in [...] => Lorsqu'on met un repertoire en dépôt

=== Check out

  Retrait

=== To check out

  Retirer, récupérer (parfois rapatrier est une bonne alternative)

=== To commit

  Consigner

=== Stage area

  Zone d'attente

=== To stage

  Mettre en attente

  Eviter _mettre en zone d'attente_

=== To unstage



=== Change

  Modification (à préférer à changement)

=== stash

  Remise

=== To stash

  Remiser

=== Checksum

  Somme de contrôle

=== Hash

  Empreinte

  Alternatives: signature, hachage (correct mais à éviter)

=== Workflow

  Processus

  Alternative: scénario

=== Snapshot

  Instantané

  Alternative: image, parfois, le choix de la traduction litérale 'photographie' est supérieur (rare)

=== Diff

  Diff

=== To track

  Suivre

=== untracked

  non-suivi

=== unmodified

  non-modifié

=== To update

  Mettre à jour

=== Translation Status

Au fur et à mesure que le travail est traduit, veuillez mettre à jour le fichier `status.json` pour indiquer le pourcentage approximatif de complétion de chaque fichier.
Cela sera présenté sur différentes pages pour que les gens sachent combien de travail il reste à faire.
